name: Build

on:
  push:
    branches:
      - main`
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
        id: go

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check go mod tidy is up to date
        run: go mod tidy && git diff --exit-code

      - name: Dump GitHub context
# Print the ENV .. debugging
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
          sudo apt-get install libpcap0.8-dev  
      - name: Build
        run: make build 
