name: Publish
# comment

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  release_and_brew:
    name: Release and bump homebrew version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        id: go
        with:
          go-version: 1.21
        env:
          #CGO_LDFLAGS: '-linkmode external -extldflags -static -O2 -g -l/usr/lib/libpcap.a'
          #CGO_LDFLAGS: '-Wl,-static -L/usr/lib/x86_64-linux-gnu/libpcap.a -lpcap -Wl,-Bdynamic'
          CGO_LDFLAGS: '-g -O2 -Wno-return-local-addr'
          GOOS: linux
          GOARCH: amd64

      - name: Get dependencies
        run: |
          sudo apt-get install -yy --fix-missing libpcap-dev xz-utils p7zip-full binutils-mingw-w64 *-w64-x86-*
          #sudo apt-get install libcap2-dev
          #sudo apt-get install libpcap-dev
          #sudo find / -name libpcap.a

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 1

