name: Publish
# comment

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  release_and_brew:
    name: Release and bump homebrew version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        id: go
        with:
          go-version: 1.21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get dependencies
        run: |
          sudo apt-get install libpcap-dev

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: 2
          version: latest
          args: release --clean  --config goRelease.cfg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
