name: Publish
# comment

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  release_and_brew:
    name: Release and bump homebrew version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        id: go
        with:
          go-version: 1.21
          #go-version: 1.19.4 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get dependencies
        run: |
          sudo apt-get install -yy --fix-missing libpcap-dev xz-utils p7zip-full binutils-mingw-w64 *-w64-x86-*
          sudo apt-get install libcap2-dev
          sudo apt-get install libpcap-dev
          sudo apt-get install gcc-multilib
          sudo apt-get install build-essential
          sudo apt-get install gcc -y
          #sudo find / -name libpcap.a

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: 2
          args: release --clean --config myGoRelease.cfg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #CGO_ENABLED: 1
          #goos: linux,windows,darwin
          #GOOS: linux,windows
          #GOARCH: 386,amd64
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@dckr_pat_L-LIh4hnjGYhZRNyrY_IUyFjRbE
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@dckr_pat_L-LIh4hnjGYhZRNyrY_IUyFjRbE
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dckr_pat_L-LIh4hnjGYhZRNyrY_IUyFjRbE
        with:
          images: |
            gressdave58/goReleaserPacket
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@dckr_pat_L-LIh4hnjGYhZRNyrY_IUyFjRbE
        with:
          context: .
          push: true
          tags: gressdave58/goReleaserPacket:latest, gressdave58/goReleaserPacket:${{ github.event.client_payload.new-tag }}

