name: Publish
# comment

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  release_and_brew:
    name: Release and bump homebrew version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        id: go
        with:
          go-version: 1.21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get dependencies
        run: |
          #sudo apt-get install -yy --fix-missing libpcap-dev xz-utils p7zip-full binutils-mingw-w64 *-w64-x86-*
          #sudo apt-get install libcap2-dev
          sudo apt-get install libpcap-dev
          #sudo apt-get install gcc-multilib
          #sudo find / -name libpcap.a

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: 2
          args: release --clean --config myGoRelease.cfg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #CGO_ENABLED: 1
          #goos: linux,windows,darwin
          #GOOS: linux,windows
          #GOARCH: 386,amd64
